## Imports

In [1]:
%load_ext autoreload
%autoreload 2
import os, sys

import envbash
envbash.load.load_envbash('../env')

sys.path.append('/Users/yvesmartin/src/rouskinhf')

from rouskinhf import convert

# Create a datafolder from local files

These methods will allow you to process your data and create a datafolder from it. The accepted formats are:
- DREEM output
- fasta
- set of CTs
- already formatted json + info.json

**Make sure to change the paths to your own paths!**

### From DREEM output

In [6]:
%reload_ext autoreload
%autoreload 2
# Show all arguments
data = convert(format='fasta', 
              file_or_folder='/Users/yvesmartin/src/rouskinhf/data/input_files_for_testing/test_sequences.fasta',
              name='test_sequences_fasta',
              path_out='../data/testing',
              predict_structure=True,
              filter=True,   
              verbose=False)
data

Parsing fasta file: 100%|██████████| 5/5 [00:00<00:00, 28.18it/s]


{'RF02271.fa.csv_1': {'sequence': 'AAACCCCAGUAGGGGUUU',
  'structure': [[0, 17],
   [1, 16],
   [2, 15],
   [3, 14],
   [4, 13],
   [5, 12],
   [6, 11]]},
 'RF02271.fa.csv_2': {'sequence': 'UUUCCCCUAGUAUGGGGAAA',
  'structure': [[1, 18], [2, 17], [3, 16], [4, 15], [5, 14], [6, 13]]},
 'RF02271.fa.csv_2_1': {'sequence': 'UUUCGCGAGGCCGAGGAAA',
  'structure': [[0, 17], [1, 16], [2, 15], [3, 14], [5, 12], [6, 11]]}}

### From a data.json file

In [25]:
data = convert(format='json', 
              file_or_folder='/Users/yvesmartin/src/rouskinhf/data/input_files_for_testing/test_sequences.fasta',
              name='test_sequences_fasta',
              path_out='data',
              predict_structure=True,
              filter=True,   
              verbose=False)

Parsing json file: 100%|██████████| 16674/16674 [00:00<00:00, 26797.20it/s]


Over a total of 16674 datapoints, there are:
    - 16674 valid datapoints
    - 0 invalid datapoints (ex: sequence with non-regular characters)
    - 0 datapoints with the same reference
    - 0 duplicate sequences with the same structure / dms
    - 0 duplicate sequences with different structure / dms
    - 0 datapoints removed because of low AUROC (<0.8)


### From a list of CT files

In [20]:
%reload_ext autoreload
%autoreload 2
datafolder = DataFolder.from_ct_folder(
    name='bpRNA', # name of the input data by default
    path_in='/Users/ymdt/Downloads/bpRNA', 
    path_out='/Users/ymdt/src/rouskinhf/data/datafolders', 
    predict_dms=False, # won't take the structure from the ct files into account
    tqdm=True, 
    generate_npy=True,
    )  

ValueError: The ct file `/Users/ymdt/Downloads/bpRNA/bpRNA_CRW_35841.ct` is not formatted correctly. Please check the file and try again. ValueError: too many values to unpack (expected 6)


### From fasta

In [2]:
datafolder = DataFolder.from_fasta(
    name= 'sequences', # name of the input data by default
    path_in = '/Users/ymdt/src/rouskinhf/data/input_files_for_testing/sequences.fasta', 
    path_out='/Users/ymdt/src/rouskinhf/data/datafolders', 
    predict_structure=True,
    predict_dms=True,
    tqdm=True,
    generate_npy=True,
    )
np.load(datafolder.get_dms_npy(), allow_pickle=True)

Parsing fasta file: 100%|██████████| 5/5 [00:01<00:00,  3.77it/s]

Over a total of 5 datapoints, there are:
    - 2 valid datapoints
    - 1 invalid datapoints (ex: sequence with non-regular characters)
    - 1 datapoints with the same reference
    - 1 duplicate sequences with the same structure / dms
    - 0 duplicate sequences with different structure / dms


array([array([3.3176258e-01, 8.6194777e-01, 9.8495054e-01, 9.9978286e-01,
              9.9995619e-01, 9.9994540e-01, 9.9702460e-01, 3.2988770e-10,
              1.0113345e-08, 9.3018784e-09, 2.1481183e-10, 9.9695349e-01,
              9.9997377e-01, 9.9998462e-01, 9.9979717e-01, 9.8487574e-01,
              8.6187601e-01, 3.3190918e-01], dtype=float32)              ,
       array([2.3766817e-01, 8.4576339e-01, 9.8692513e-01, 9.9954951e-01,
              9.9981171e-01, 9.9981171e-01, 9.9900937e-01, 7.4752042e-04,
              1.4492057e-03, 5.6404242e-11, 0.0000000e+00, 0.0000000e+00,
              1.4492056e-03, 9.9931222e-01, 9.9998856e-01, 9.9998885e-01,
              9.9991626e-01, 9.8716962e-01, 8.4594077e-01, 2.3697025e-01],
             dtype=float32)                                               ],
      dtype=object)

### From an existing local datafolder

In [4]:
datafolder = DataFolder.from_local(
    name = '/Users/ymdt/src/rouskinhf/data/datafolders/for_testing',
)

# OR

datafolder = import_dataset(
    name = 'for_testing',
    data = 'DMS', # can be 'DMS' or 'structure'
    force_download=False # if True, will download the data even if it already exists locally
)

No folder found in data/input_files/pri-miRNA


Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Parsing json file: 100%|██████████| 503/503 [00:00<00:00, 25099.76it/s]


Over a total of 503 datapoints, there are:
    - 503 valid datapoints
    - 0 invalid datapoints (ex: sequence with non-regular characters)
    - 0 datapoints with the same reference
    - 0 duplicate sequences with the same structure / dms
    - 0 duplicate sequences with different structure / dms
    - 0 datapoints removed because of low AUROC (<0.8)
Using data from HuggingFace Hub for pri-miRNA


# Push a local datafolder to Hugging Face

### 1. Create a repository if it does not exist

In [ ]:
# Find more arguments here: https://huggingface.co/docs/huggingface_hub/guides/repository#create-a-repository
datafolder.create_repo(
    exist_ok=True,
    private=True
)

### 2. Push the datafolder to Hugging Face

In [ ]:

# Find more arguments here: https://huggingface.co/docs/huggingface_hub/guides/upload#upload-a-folder
future = datafolder.upload_folder(
    revision='main', # branch name
    commit_message='Upload demo dataset',
    commit_description='This is a demo dataset',
    run_as_future=True,
)

future.done() # True if the upload is done
future.result() # Wait for the upload to complete (blocking action)

'https://huggingface.co/datasets/rouskinlab/pri-miRNA-test/tree/main/'

### 3. Check that the datafolder is on Hugging Face

Take a look at https://huggingface.co/rouskinlab

# Explore the datafolder object

In [ ]:
import numpy as np
import json
print(datafolder)
print('main folder:',datafolder.get_main_folder())
print('sequences.npy file:\n',np.load(datafolder.get_sequences_npy(), allow_pickle=True))
print('base_pairs.npy file:\n',np.load(datafolder.get_base_pairs_npy(), allow_pickle=True))
print('dms.npy file:\n',np.load(datafolder.get_dms_npy(), allow_pickle=True))
print('json file:\n', json.load(open(datafolder.get_json(), 'r')))
print('dms.npy file:',datafolder.get_dms_npy())
print('json file:',datafolder.get_json())
print('source files:',datafolder.get_source_files())
print('info file:',datafolder.get_info_file())

In [8]:
%reload_ext autoreload
%autoreload 2
data_pri = import_dataset(
    name = 'pri-miRNA-test',
    data = 'DMS', # can be 'DMS' or 'structure'
    force_generate_npy=True, # if True, will download the data even if it already exists locally
    force_download=True
)

# data_utr = import_dataset(
#     name = 'utr',
#     data = 'DMS', # can be 'DMS' or 'structure'
#     force_download=False # if True, will download the data even if it already exists locally
# )


Force download from HuggingFace Hub


Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Parsing json file: 100%|██████████| 513/513 [00:00<00:00, 59079.57it/s]

Over a total of 513 datapoints, there are:
    - 513 valid datapoints
    - 0 invalid datapoints (ex: sequence with non-regular characters)
    - 0 datapoints with the same reference
    - 0 duplicate sequences with the same structure / dms
    - 0 duplicate sequences with different structure / dms
Using data from HuggingFace Hub for pri-miRNA-test


In [9]:
# load dms.npy 

data_pri['DMS'][0]


array([-1.000e+03, -1.000e+03, -1.000e+03, -1.000e+03, -1.000e+03,
       -1.000e+03, -1.000e+03, -1.000e+03, -1.000e+03, -1.000e+03,
       -1.000e+03, -1.000e+03, -1.000e+03, -1.000e+03, -1.000e+03,
       -1.000e+03, -1.000e+03, -1.000e+03, -1.000e+03, -1.000e+03,
       -1.000e+03, -1.000e+03, -1.000e+03, -1.000e+03, -1.000e+03,
       -1.000e+03,  4.700e-01, -1.000e+03,  5.661e-01,  3.952e-01,
        3.206e-01,  3.242e-01, -1.000e+03, -1.000e+03, -1.000e+03,
       -1.000e+03,  5.054e-01, -1.000e+03, -1.000e+03,  6.266e-01,
        1.374e-01, -1.000e+03, -1.000e+03, -1.000e+03, -1.000e+03,
        1.574e-01,  4.347e-01,  3.740e-01,  2.133e-01,  3.261e-01,
       -1.000e+03, -1.000e+03,  3.130e-01,  5.454e-01,  6.481e-01,
        5.420e-02,  5.340e-02, -1.000e+03, -1.000e+03, -1.000e+03,
        8.170e-02, -1.000e+03, -1.000e+03, -1.000e+03, -1.000e+03,
        3.690e-01, -1.000e+03,  1.570e-01, -1.000e+03, -1.000e+03,
        3.140e-02,  8.870e-02,  5.650e-02, -1.000e+03, -1.000e

In [2]:
import numpy as np
a = np.array([np.array([0,1,2,3]), np.array([2,3,4])], dtype=object)

In [15]:
a = [1, 2]; b= [3, 4, 5]
np.array([np.array(a, dtype=np.float32), np.array(b, dtype=np.float32)], dtype=object)


array([array([1., 2.], dtype=float32), array([3., 4., 5.], dtype=float32)],
      dtype=object)

In [16]:

c, b = [0.1321452463246523462346532, 0.1321452463246523462346532], [0.1321452463246523462346532, 0.1321452463246523462346532]
np.array([np.array(c, dtype=np.float32), np.array(b, dtype=np.float32)], dtype=object)


array([[0.1321452409029007, 0.1321452409029007],
       [0.1321452409029007, 0.1321452409029007]], dtype=object)